### PR TITLE
Make it possible to specify a custom clusterDomain

### PR DESCRIPTION
**Pull request by fibbers**
…  if it differs from the default `cluster.local`.

A new field `clusterDomain` is added and if not specified, it falls back to the default of `cluster.local`.

Note that if you modify a `MinIOInstance`, the `StatefulSet` resource is _not_ modified currently in this commit.
So it's only taken into account when creating a `MinIOInstance`.

This should help for issue #70 and issue minio/minio#6775.

NB: I tested it by building a new image and deploying it to my own k8s-cluster (both specifying the `clusterDomain` property and leaving it out).

Lastly, I'm not that familiar in Go, so I tried until it worked 😄 let me know if there are other things that need to be modified or taken into account

This is the yaml I tried:
```yaml
apiVersion: miniocontroller.min.io/v1beta1
kind: MinIOInstance
metadata:
  name: minio
spec:
  clusterDomain: custom.domain.example.com <--
  selector:
    matchLabels:
      app: minio # Should match spec.metadata.labels
  ## Add metadata to the all pods created by the StatefulSet
  metadata:
    labels:
      app: minio # Should match spec.selector.matchLabels
    annotations:
      prometheus.io/path: /minio/prometheus/metrics
      prometheus.io/port: "9000"
      prometheus.io/scrape: "true"
  ## Registry location and Tag to download MinIO Server image
  image: minio/minio:RELEASE.2020-01-03T19-12-21Z
  ...
```

### CODE REVIEW

**Comment by nitisht** [comment]
Thanks for the PR @fibbers looks good. I'll test locally once then we can take it in

**Comment by nitisht** [comment]
@fibbers I tried, it did not work when I set a custom domain, have you tried this locally?

**Comment by fibbers** [comment]
Hmm, when creating the PR I saw I had a merge conflict, so I resolved it on github.com itself. Didn't try the new resolved merge result though.

Now that I try the new result, I get errors from the operator deployment when deploying a new minio instance:
```
│ minio-operator E0417 07:18:17.715418       1 runtime.go:66] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] w
│ ith length 0)
│ minio-operator /Users/willem/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181015213631-60666be32c5d/pkg/util/runtime/runtime.go:72
│ minio-operator /Users/willem/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181015213631-60666be32c5d/pkg/util/runtime/runtime.go:65
│ minio-operator /Users/willem/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181015213631-60666be32c5d/pkg/util/runtime/runtime.go:51
│ minio-operator /usr/local/Cellar/go/1.14.1/libexec/src/runtime/panic.go:967
│ minio-operator /usr/local/Cellar/go/1.14.1/libexec/src/runtime/panic.go:88
│ minio-operator /Users/willem/git_reps/minio-operator/pkg/resources/statefulsets/statefulset.go:144
│ minio-operator /Users/willem/git_reps/minio-operator/pkg/resources/statefulsets/statefulset.go:251
│ minio-operator /Users/willem/git_reps/minio-operator/pkg/controller/cluster/controller.go:333
│ minio-operator /Users/willem/git_reps/minio-operator/pkg/controller/cluster/controller.go:248
│ minio-operator /Users/willem/git_reps/minio-operator/pkg/controller/cluster/controller.go:256
│ minio-operator /Users/willem/git_reps/minio-operator/pkg/controller/cluster/controller.go:209
│ minio-operator /Users/willem/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181015213631-60666be32c5d/pkg/util/wait/wait.go:133
│ minio-operator /Users/willem/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181015213631-60666be32c5d/pkg/util/wait/wait.go:134
│ minio-operator /Users/willem/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181015213631-60666be32c5d/pkg/util/wait/wait.go:88
│ minio-operator /usr/local/Cellar/go/1.14.1/libexec/src/runtime/asm_amd64.s:1373
│ minio-operator panic: runtime error: index out of range [0] with length 0 [recovered]
│ minio-operator     panic: runtime error: index out of range [0] with length 0
│ minio-operator goroutine 93 [running]:
│ minio-operator k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
│ minio-operator     /Users/willem/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181015213631-60666be32c5d/pkg/util/runtime/runtime.go:58 +0x105
│ minio-operator panic(0x111b7a0, 0xc0006677c0)
│ minio-operator     /usr/local/Cellar/go/1.14.1/libexec/src/runtime/panic.go:967 +0x166
│ minio-operator github.com/minio/minio-operator/pkg/resources/statefulsets.minioServerContainer(0xc0000b8240, 0xc000122d60, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
│ minio-operator     /Users/willem/git_reps/minio-operator/pkg/resources/statefulsets/statefulset.go:144 +0x63a
│ minio-operator github.com/minio/minio-operator/pkg/resources/statefulsets.NewForCluster(0xc0000b8240, 0xc000122d60, 0xc, 0x8)
│ minio-operator     /Users/willem/git_reps/minio-operator/pkg/resources/statefulsets/statefulset.go:251 +0x3b0
│ minio-operator github.com/minio/minio-operator/pkg/controller/cluster.(*Controller).syncHandler(0xc0003ac000, 0xc000122d30, 0xb, 0xc0001746c0, 0xc000519db0)
│ minio-operator     /Users/willem/git_reps/minio-operator/pkg/controller/cluster/controller.go:333 +0xcb4
│ minio-operator github.com/minio/minio-operator/pkg/controller/cluster.(*Controller).processNextWorkItem.func1(0xc0003ac000, 0x100d220, 0xc00001c870, 0x0, 0x0)
│ minio-operator     /Users/willem/git_reps/minio-operator/pkg/controller/cluster/controller.go:248 +0x149
│ minio-operator github.com/minio/minio-operator/pkg/controller/cluster.(*Controller).processNextWorkItem(0xc0003ac000, 0x0)
│ minio-operator     /Users/willem/git_reps/minio-operator/pkg/controller/cluster/controller.go:256 +0x50
│ minio-operator github.com/minio/minio-operator/pkg/controller/cluster.(*Controller).runWorker(0xc0003ac000)
│ minio-operator     /Users/willem/git_reps/minio-operator/pkg/controller/cluster/controller.go:209 +0x2b
│ minio-operator k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00049f260)
│ minio-operator     /Users/willem/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181015213631-60666be32c5d/pkg/util/wait/wait.go:133 +0x5f
│ minio-operator k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00049f260, 0x3b9aca00, 0x0, 0x1, 0xc0000889c0)
│ minio-operator     /Users/willem/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181015213631-60666be32c5d/pkg/util/wait/wait.go:134 +0xf8
│ minio-operator k8s.io/apimachinery/pkg/util/wait.Until(0xc00049f260, 0x3b9aca00, 0xc0000889c0)
│ minio-operator     /Users/willem/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181015213631-60666be32c5d/pkg/util/wait/wait.go:88 +0x4d
│ minio-operator created by github.com/minio/minio-operator/pkg/controller/cluster.(*Controller).Run
│ minio-operator     /Users/willem/git_reps/minio-operator/pkg/controller/cluster/controller.go:195 +0x272
```
When reading the stack, I see lines that are modified in 465da3308f1ddbfe0cdea9f6048c2baa8352423e so something seems incompatible, though I'll check more closely when I have more time. (I'm open to suggestions of course.)

**Comment by fibbers** [comment]
@nitisht  I had another look at it and when I modified my yaml file a bit with the `zones` field I got it working.

To give full details, this yaml file is what I applied (both with and without setting `clusterDomain`):
```yaml
apiVersion: miniocontroller.min.io/v1beta1
kind: MinIOInstance
metadata:
  name: minio
  namespace: minio
spec:
  clusterDomain: k8s.example.com <-- masked value here :)
  selector:
    matchLabels:
      app: minio # Should match spec.metadata.labels
  metadata:
    labels:
      app: minio # Should match spec.selector.matchLabels
    annotations:
      prometheus.io/path: /minio/prometheus/metrics
      prometheus.io/port: "9000"
      prometheus.io/scrape: "true"
  image: minio/minio:RELEASE.2020-01-03T19-12-21Z
  zones:
    - name: "zone-0"
      servers: 4
  volumesPerServer: 1
  mountPath: /export
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      storageClassName: nfs-client
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  credsSecret:
    name: minio-creds-secret
  podManagementPolicy: Parallel
  requestAutoCert: false
  certConfig:
    commonName: ""
    organizationName: []
    dnsNames: []
  env:
    - name: MINIO_BROWSER
      value: "on"
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
  liveness:
    httpGet:
      path: /minio/health/live
      port: 9000
    initialDelaySeconds: 120
    periodSeconds: 20
  readiness:
    httpGet:
      path: /minio/health/ready
      port: 9000
    initialDelaySeconds: 120
    periodSeconds: 20
```

I only see errors inside the `minio` pods initially but they disappear after 2 minutes and the pods seem to be running okay (except when I leave out the `clusterDomain` field, of course). The `minio-operator` pod doesn't give any errors in my cluster.

What kind of errors do you see?

**Comment by fibbers** [comment]
And to answer your question more detailed:

> have you tried this locally?

I tried it locally in that it's a private cluster installed on bare metal machines, but it's not local in the sense that it's minikube or similar.
Hope that answers your question.

**Comment by nitisht** [comment]
Thanks @fibbers . I will test this out again.

**Comment by nitisht** [comment]
@fibbers closing this in favour of #84 . Thanks again for all your effort

**Pull request closed without merging**
