### PR TITLE
Update minio-operator clusterrole and remove a less necessary event

### PR DESCRIPTION
**Pull request by chaoleili**
Add event in clusterrole to make minio-operator could create event
resource to kube-apiserver.
Minio-operator also need to use statefulsets watch api in statefulset
informer.

### CODE REVIEW

**Comment by chaoleili** [comment]
If we allow minio-operator to send events to kube-apiserver. The SuccessSynced event at every time of syncHandler is too frequent. And I think is better to remove this.

**Comment by nitisht** [comment]
> Add event in clusterrole to make minio-operator could create eventresource to kube-apiserver.

@chaoleili could you please elaborate how does this help, I mean why is the event needed for minio-operator

**Comment by chaoleili** [comment]
add event is helpful for getting more information when minioInstances updated or other related object updated. In minio-operator controller define a event recorder: https://github.com/minio/minio-operator/blob/2277b8f9417dd3b1dc5b4df39b1ac4226a7b865d/pkg/controller/cluster/controller.go#L128
and use it to send some events, eg:  https://github.com/minio/minio-operator/blob/2277b8f9417dd3b1dc5b4df39b1ac4226a7b865d/pkg/controller/cluster/controller.go#L325 If minio-operator has no event authority. Events send by minio-operator will be rejected by kube-apiserver.

**Comment by nitisht** [comment]
> If minio-operator has no event authority. Events send by minio-operator will be rejected by kube-apiserver.

Thanks @chaoleili makes sense.

**Comment by nitisht** [comment]
cc // @wlan0

**Pull request merged**
