### PR TITLE
Add flag for go template to format host names

### PR DESCRIPTION
**Pull request by dmayle**
When using an alternate DNS like external-dns, your host names will be
different than the internal core-dns format.  This adds a flag so that
the user can specify the name format using a go template.

### CODE REVIEW

**Comment by dmayle** [comment]
I've updated the docs and merged in recent changes

**Comment by dmayle** [comment]
I can't seem to figure out how to mark that I've made the changes requested @harshavardhana

**Comment by harshavardhana** [comment]
> I can't seem to figure out how to mark that I've made the changes requested @harshavardhana 

There is no such thing in GitHub AFAIK @dmayle

**Comment by kerneltime** [comment]
Code looks good any chance you can add a test for https://github.com/minio/minio-operator/pull/130/files#diff-5fba95502c597c71c1ec5de3290ef01bR235

**Comment by dmayle** [comment]
@kerneltime added a test for the various template variables.
@nitisht  done and done.

**Pull request merged**
