### PR TITLE
make minio image configurable

### PR DESCRIPTION
**Pull request by phin1x**
In our environment, we are not allowed to use images from docker hub. This pull request makes the minio image configurable via a command line argument. So a custom registry can be used.

### CODE REVIEW

**Comment by harshavardhana** [comment]
This will be taken in another PR

**Comment by nirnanaaa** [comment]
why was this closed? I don't see this as a reason to reject this PR, as it came first, right?

**Comment by harshavardhana** [comment]
> why was this closed? I don't see this as a reason to reject this PR, as it came first, right?

It was incomplete @nirnanaaa and its merged already.

**Comment by nirnanaaa** [comment]
ok, sounded a bit harsh your response, could you link to the pr/commit?

**Comment by harshavardhana** [comment]
> ok, sounded a bit harsh your response, could you link to the pr/commit?

That wasn't the intention - since the entire project was being refactored it made sense to take it in. 

```
commit 1d2a6c49cbae00402f36f61e91b162ff3b09446c (HEAD -> master, origin/master, origin/HEAD)
Author: Harshavardhana <harsha@minio.io>
Date:   Wed Jun 26 11:42:30 2019 -0700

    Migrate to go1.12 only builds, change license to MinIO

commit 1660ff884956c09548d7081772054536ea9e9f06
Author: Fabian <fabian@example.com>
Date:   Tue Jun 11 19:48:45 2019 +0200

    make minio image configurable
```

**Pull request closed without merging**
