### PR TITLE
WIP: Add Prometheus servicemonitor definition for Minio

### PR DESCRIPTION
**Pull request by OchiengEd**
This PR is a work in progress and attempts to automatically add a Prometheus `servicemonitor` to the cluster if the prometheus API exists.

### CODE REVIEW

**Comment by nitisht** [comment]
Thanks for the PR @OchiengEd , we’ll take a look, meanwhile I did something similar here, https://github.com/minio/m3/pull/211 may be this is helpful

**Comment by OchiengEd** [comment]
> Thanks for the PR @OchiengEd , we’ll take a look, meanwhile I did something similar here, [minio/m3#211](https://github.com/minio/m3/pull/211) may be this is helpful

Looking into what you've done so far

**Comment by OchiengEd** [comment]
@nitisht  From the code review, your PR creates a new prometheus deployment and configures it to scrape metrics from minio. My PR attempts to do something similar but using a different approach. So it is acceptable to close this PR.

**Comment by nitisht** [comment]
@OchiengEd my PR was for another project. You are more than welcome to implement it in this repo.

**Comment by harshavardhana** [comment]
can the build issue be fixed @OchiengEd ?

**Comment by nitisht** [comment]
okay

**Pull request closed without merging**
